{
  pkgs,
  myvars,
  ...
}: {
  services.greetd = {
    enable = true;
    useTextGreeter = true;
    settings = {
      default_session = {
        # .wayland-session is a script generated by home-manager, which links to the current wayland compositor(sway/hyprland or others).
        # with such a vendor-no-locking script, we can switch to another wayland compositor without modifying greetd's config here.
        # command = "$HOME/.wayland-session"; # start a wayland session directly without a login manager
        # command = "${pkgs.tuigreet}/bin/tuigreet --time --cmd $HOME/.wayland-session"; # start wayland session with a TUI login manager
        command = "${pkgs.tuigreet}/bin/tuigreet --time --cmd niri-session";
        user = myvars.username;
      };
    };
  };
  # services.displayManager.ly = {
  #   enable = true;
  #   settings = {
  #     # The active animation
  #     # none     -> Nothing
  #     # doom     -> PSX DOOM fire
  #     # matrix   -> CMatrix
  #     # colormix -> Color mixing shader
  #     # gameoflife -> John Conway's Game of Life
  #     # dur_file -> .dur file format (https://github.com/cmang/durdraw/tree/master)
  #     # config example at https://codeberg.org/fairyglade/ly/src/branch/master/res/config.ini#L21
  #     animation = "colormix";
  #     clock = "%H:%M";
  #     bigclock = "en";
  #     hide_borders = true;
  #     blank_box = true;
  #     center = true;
  #     bg = 0;
  #     fg = 2;
  #     input_fg = 4;
  #     battery_id = "BAT1";
  #   };
  # };
}
